Repository nginx/nginx-prometheus-exporter, pull requests merged in 2021-03, with the labels that each got.

#158 Remove unused labels
  .github/release-drafter.yml
Labels: chore

#159 Add GitHub workflow to check for stale PRs and issues
  .github/workflows/stale.yml
Labels: chore

#160 Update Go version to 1.16
  .github/workflows/ci.yml
  .github/workflows/fossa.yml
  build/Dockerfile
  go.mod
Labels: dependencies

#155 Use equal sign in cli args examples
  README.md
Labels: documentation

#163 Add GoReleaser and fix missing vars in CI workflow
  .github/workflows/ci.yml
  .gitignore
  .goreleaser.yml
  Makefile
  build/Dockerfile
  exporter.go
  go.sum
Labels: bug, chore, dependencies, proposal

#164 Add support for more platforms, push to Docker Hub
  .github/workflows/ci.yml
  .goreleaser.yml
  Makefile
  build/Dockerfile
Labels: chore, enhancement

#167 Use scratch to support building for more archs
  .github/workflows/ci.yml
  build/Dockerfile
Labels: chore

#169 Add date to binary when building locally
  Makefile
  build/Dockerfile
Labels: chore

#165 Release 0.9.0
  CHANGELOG.md
  Makefile
  README.md
Labels: chore, documentation

#170 Fix release order
  .github/workflows/ci.yml
Labels: bug
