Repository nginx/nginx-prometheus-exporter, pull requests merged in 2021-04, with the labels that each got.

#175 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore

#174 Move dependencies into separate category
  .github/release-drafter.yml
Labels: chore

#176 Add golangci-lint as a dependency
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  tools.go
Labels: dependencies

#177 Use Fossa action in the workflow
  .github/workflows/fossa.yml
Labels: chore

#180 Update badge for Fossa
  README.md
Labels: chore, documentation

#183 Fix upstream server fails metric description
  collector/nginx_plus.go
Labels: documentation
