Repository nginx/nginx-prometheus-exporter, pull requests merged in 2023-11, with the labels that each got.

#540 add cache metrics for NGINX plus
  README.md
  collector/nginx_plus.go
  exporter.go
Labels: documentation

#530 Add metrics from NGINX Plus API version 9
  README.md
  collector/nginx_plus.go
  exporter.go
Labels: enhancement, documentation

#549 Update CODEOWNERS
  CODEOWNERS
Labels: chore

#539 Add support for multiple scrape addresses
  README.md
  exporter.go
Labels: documentation
