Repository nginx/nginx-prometheus-exporter, pull requests merged in 2024-06, with the labels that each got.

#733 Add more linters
  .github/PULL_REQUEST_TEMPLATE.md
  .golangci.yml
  collector/nginx_plus.go
  exporter.go
  exporter_test.go
Labels: documentation, chore, tests

#749 Update stale.yml
  .github/workflows/stale.yml
Labels: chore

#650 Fix systemd example for configuring nginx_exporter.service
  examples/systemd/nginx_exporter.service
Labels: bug, community
