Repository nginx/nginx-prometheus-exporter, pull requests merged in 2024-01, with the labels that each got.

#586 Restore SCRAPE_URI env var
  exporter.go
Labels: bug

#587 Set permissions to close milestones for GoReleaser
  .github/workflows/ci.yml
Labels: chore

#581 Add config to publish Nix packages
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: enhancement

#583 Add config to publish scoop packages
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: enhancement

#598 Release 1.1.0
  Makefile
  README.md
Labels: documentation

#599 Fix GoReleaser config
  .goreleaser.yml
Labels: chore

#607 Add Environment Variable options to flags managed in exporter-toolkit
  README.md
  exporter.go
  exporter_test.go
Labels: documentation, tests
