Repository nginx/nginx-prometheus-exporter, pull requests merged in 2024-07, with the labels that each got.

#755 Update CodeQL workflow
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
Labels: chore

#756 Use yamllint action from reviewdog
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: chore

#763 Update Live Monitoring link
  README.md
Labels: documentation

#754 Add GitHub Action workflow for F5 CLA integration
  .github/workflows/f5-cla.yml
  CONTRIBUTING.md
Labels: documentation

#777 Remove unnecessary variable labels for workers
  README.md
  collector/nginx_plus.go
  exporter.go
Labels: enhancement, documentation

#779 Add linters that check for bugs
  .golangci.yml
  collector/nginx_plus.go
Labels: chore

#783 Add release process
  release-process.md
Labels: documentation

#780 Fix Cache to use variable labels
  collector/nginx_plus.go
Labels: bug

#781 Revert "switch from warning to debug when upstream labels are empty (#724)"
  collector/nginx_plus.go
Labels: bug

#782 Release 1.3.0
  Makefile
  README.md
Labels: documentation
