Repository nginx/nginx-prometheus-exporter, pull requests merged in 2025-08, with the labels that each got.

#1107 Switch to DialContext() to address lint issue
  exporter.go
Labels: chore

#1108 Update nginx-plus-go-client to v3.0.0
  collector/nginx_plus.go
  exporter.go
  go.mod
  go.sum
Labels: dependencies

#979 Add proxy protocol v2 client-side support
  README.md
  exporter.go
  go.mod
  go.sum
Labels: documentation, dependencies
